spring:
  application:
    name: authentication

server:
  port: 9004

auth-server:
  url: http://localhost:8888
  realms: auth-service
  client-id: auth-service-client
  client_secret: iBnKyxhwMPcY7PcXDyBHqZFO6gRawg8C
