


spring:
  application:
    name: order

  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password

  jpa:
    generate-ddl: true
    show-sql: true

  profiles:
    default: test

logging:
  level:
    org.springframework.amqp.rabbit.core.RabbitTemplate: info
    nuts.lib.manager.broker_manager.rabbitmq: debug

server:
  port:  9004


stock_server_url: http://localhost:9811/