spring:
  application:
    name: member

  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password

  jpa:
    generate-ddl: true
    show-sql: true

  profiles:
    active: dev
server:
  port: 9001
