spring:
  application:
    name: gateway

  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password

#  cloud:
#    gateway:
#      routes:
#        - id: test
#          uri: http://localhost:9004/orders/harunuts
#          predicates:
#            - Path=/test

routing:
  routing-table:
    member-service:
      url: localhost
      port: 9001

    order-service:
      url: localhost
      port: 9002

    stock-service:
      url: localhost
      port: 9003

    authentication-service:
      url: localhost
      port: 9004

server:
  port: 9000

