spring:
  application:
    name: gateway


  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password

#  cloud:
#    gateway:
#      routes:
#        - id: test
#          uri: http://localhost:9004/orders/harunuts
#          predicates:
#            - Path=/test




server:
  port: 9006

