spring:
  application:
    name: gateway
#  cloud:
#    gateway:
#      routes:
#        - id: test
#          uri: http://localhost:9004/orders/harunuts
#          predicates:
#            - Path=/test


server:
  port: 9006

