name: CI

on: push
jobs:
  push-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Verify Java version
        run: java -version

      - name: Grant execute permission for gradlew
        run: |
          cd order
          chmod +x ./gradlew

      # Gradle test 실행 (특정 모듈)
      - name: Test module A with Gradle
        run: | 
          cd order
          ./gradlew --info test
